inherit_from:
  - .rubocop_airbnb.yml

Rails:
  # Rails 用に最適化されたモードにする設定、基本はtrue
  Enabled: true

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/**/*'
    - 'spec/*'

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Layout/FirstHashElementLineBreak:
  Enabled: false

Airbnb/OptArgParameters:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/MutableConstant:
  Enabled: false
