version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/cook-paad
    ports:
      - "3000:3000"
    depends_on:
      - db

# dockerは先にgemfileなどを作っておいてそこからnewして作成していく
# docker-compose run web rails new . --force --no-deps --database=postgresql --skip-bundle
